FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libssl-dev

RUN git clone https://github.com/ggerganov/llama.cpp.git
WORKDIR /llama.cpp

RUN make

COPY other/genai_models/llama-2-13b-chat.Q4_K_M.gguf /llama.cpp/models

EXPOSE 8080

CMD ["./server", "-m", "models/llama-2-13b-chat.Q4_K_M.gguf", "-c", "2048", "--host", "0.0.0.0"]
