# Generated by Django 5.0 on 2024-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                ("id",
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name="ID",
                 ),
                 ),
                ("file",
                 models.FileField(
                     upload_to="audios/")),
                ("floating_point_number",
                 models.FloatField(
                     blank=True,
                     null=True)),
            ],
        ),
    ]
