# Generated by Django 5.0 on 2024-01-03 13:35
# pylint: disable=all
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audio_endpoint", "0002_audiofile_audio_name_audiofile_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="audio_name",
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="updated_at",
        ),
    ]
