# Generated by Django 5.0 on 2024-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_endpoint", "0003_remove_audiofile_audio_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="file",
            field=models.CharField(max_length=100),
        ),
    ]
