# Generated by Django 5.0 on 2024-01-07 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_endpoint", "0004_alter_audiofile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiofile",
            old_name="file",
            new_name="file_path",
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="floating_point_number",
        ),
        migrations.AddField(
            model_name="audiofile",
            name="json_order",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
