# Generated by Django 5.0 on 2024-01-07 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_endpoint", "0006_remove_audiofile_json_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="json_order",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
