# Generated by Django 5.0 on 2024-01-08 19:43
# pylint: disable=all
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_endpoint", "0007_audiofile_json_order_audiofile_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="json_order",
            field=models.JSONField(default=list),
        ),
    ]
