# Generated by Django 5.0 on 2024-01-08 21:35
# pylint: disable=all
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_endpoint", "0008_alter_audiofile_json_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="json_order",
            field=models.JSONField(default=dict),
        ),
    ]
