# Generated by Django 5.0 on 2024-01-03 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AudioEndpoint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="audio_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="audiofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="audiofile",
            name="description",
            field=models.TextField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="audiofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
