name: backend

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/unit-test.yml'
      
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/unit-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev flac ffmpeg
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with pylint
      run: |
        pylint src/*.py

    - name: Test with pytest
      run: python -m coverage run --branch --source=scripts -m -k pytest --ignore=tests/test_audio_endpoint ./tests/

    - name: Test with Djanngo
      run: python manage.py test
